# Generated by Django 3.0.7 on 2020-06-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_tagalongs'),
        ('trips', '0002_allow_null_activity_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pickup_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_verified': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_driver', to='accounts.Driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_verified': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_driver', to='accounts.Driver'),
        ),
    ]
