# Generated by Django 3.0.7 on 2020-06-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_datetime', models.DateTimeField()),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=6)),
                ('activity_partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trips.ActivityPartner')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(blank=True, max_length=100)),
                ('pickup_datetime', models.DateTimeField(db_index=True, null=True)),
                ('pickup_completed', models.BooleanField(default=False)),
                ('pickup_driver_notes', models.CharField(blank=True, max_length=500)),
                ('pickup_family_notes', models.CharField(blank=True, max_length=500)),
                ('return_datetime', models.DateTimeField(db_index=True, null=True)),
                ('return_completed', models.BooleanField(default=False)),
                ('return_driver_notes', models.CharField(blank=True, max_length=500)),
                ('return_family_notes', models.CharField(blank=True, max_length=500)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_datetime', models.DateTimeField(null=True)),
                ('car_seat_required', models.BooleanField(default=False)),
                ('booster_seat_required', models.BooleanField(default=False)),
                ('special_needs', models.CharField(blank=True, max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Event')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Family')),
                ('passengers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.FamilyMember')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.FamilyAddress')),
                ('pickup_driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_driver', to='accounts.Driver')),
                ('return_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.FamilyAddress')),
                ('return_driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_driver', to='accounts.Driver')),
            ],
        ),
    ]
